# Generated by Django 4.2.7 on 2023-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=50)),
                ('arrival_city', models.CharField(max_length=50)),
                ('arrival_airport', models.CharField(max_length=50)),
                ('departure_day', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_day', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('aviation_company', models.CharField(max_length=50)),
                ('spare_economy', models.IntegerField()),
                ('spare_business', models.IntegerField()),
                ('price_economy', models.IntegerField()),
                ('price_business', models.IntegerField()),
                ('plane', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightID', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ticket_class', models.CharField(max_length=50)),
            ],
        ),
    ]
