# Generated by Django 4.2.7 on 2023-12-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='userID',
            field=models.CharField(max_length=60),
        ),
    ]
